# Generated by Django 4.2.11 on 2026-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_webauthn_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('WITHDRAWAL', 'Withdrawal Request'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('DEAL_CREATED', 'Deal Created'), ('DEAL_FUNDED', 'Deal Funded'), ('DEAL_COMPLETED', 'Deal Completed'), ('DEAL_DISPUTED', 'Deal Disputed'), ('DEAL_CANCELLED', 'Deal Cancelled'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('ADMIN_ACTION', 'Admin Action'), ('PASSKEY_LOGIN', 'Passkey Login'), ('PASSKEY_REGISTERED', 'Passkey Registered')], max_length=50),
        ),
    ]
