# Generated by Django 4.2.11 on 2026-04-23 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ESCROW_LOCK', 'Escrow Lock'), ('ESCROW_RELEASE', 'Escrow Release'), ('FEE', 'Platform Fee'), ('REFUND', 'Refund')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('balance_before', models.DecimalField(decimal_places=6, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=6, max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ledger_entr_user_id_ac6f8f_idx'), models.Index(fields=['deal', '-created_at'], name='ledger_entr_deal_id_289b44_idx'), models.Index(fields=['transaction_type', '-created_at'], name='ledger_entr_transac_e4069d_idx')],
            },
        ),
    ]
