# Generated by Django 4.2.11 on 2026-04-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledgerentry_transaction_hash'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='ledger_entr_transac_45160c_idx',
            old_name='ledger_entr_transac_hash_idx',
        ),
    ]
